IF NOT EXISTS (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'dbo' AND TABLE_NAME = 'FileLogs')
BEGIN
    CREATE TABLE dbo.FileLogs (
        [Id] UNIQUEIDENTIFIER PRIMARY KEY,
        [FileName] NVARCHAR(450) NOT NULL,
        [Container] NVARCHAR(255) NULL,
        [Created] DATETIME DEFAULT GETDATE(),
        [Status] INT NOT NULL,
        [Data] NVARCHAR(MAX),
        [Text] TEXT NULL,
        [Timestamp] DATETIME DEFAULT GETDATE(),
        FOREIGN KEY ([FileName]) REFERENCES Files([Name]) ON DELETE CASCADE ON UPDATE CASCADE
    );
END